# Generated by Django 3.2.3 on 2021-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='css_class',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('event-warning', 'Warning'), ('event-info', 'Info'), ('event-success', 'Success'), ('event-inverse', 'Inverse'), ('event-special', 'Special'), ('event-important', 'Important')], max_length=20, verbose_name='CSS Class'),
        ),
    ]
