# Generated by Django 3.2.3 on 2021-06-12 05:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0007_delete_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Meeting_ClientName',
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_Client_EmailID',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Host_ID',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Host_ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='Meeting_ClientID',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Meeting_ClientID', to=settings.AUTH_USER_MODEL),
        ),
    ]
