# Generated by Django 3.2.3 on 2021-06-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20210612_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Meeting_Client_EmailID',
            new_name='Meeting_Client_Email',
        ),
    ]
