# Generated by Django 3.2.3 on 2021-06-12 05:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0009_rename_meeting_client_emailid_event_meeting_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Meeting_ClientID',
        ),
        migrations.AddField(
            model_name='event',
            name='Meeting_ClientName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Host_ID',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
