# Generated by Django 3.2.3 on 2021-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20210612_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
